from enum import StrEnum


class ProviderState(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    DISABLED = "DISABLED"


class ServiceType(StrEnum):
    STARS = "STARS"
    PREMIUM = "PREMIUM"
    GIFT = "GIFT"


class OrderStatus(StrEnum):
    DRAFT = "DRAFT"
    AWAITING_PAYMENT = "AWAITING_PAYMENT"
    PAYMENT_REVIEW = "PAYMENT_REVIEW"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"
    AWAITING_PROVIDER_FUNDING = "AWAITING_PROVIDER_FUNDING"
    READY_TO_SUBMIT = "READY_TO_SUBMIT"
    SUBMITTING = "SUBMITTING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    PRICE_CHANGED = "PRICE_CHANGED"
    INSUFFICIENT_PROVIDER_FUNDS = "INSUFFICIENT_PROVIDER_FUNDS"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class LedgerType(StrEnum):
    PAYMENT_CREDIT = "PAYMENT_CREDIT"
    RESERVE = "RESERVE"
    COMPLETE = "COMPLETE"
    REFUND = "REFUND"


class PaymentStatus(StrEnum):
    AWAITING_RECEIPT = "AWAITING_RECEIPT"
    REVIEW_PENDING = "REVIEW_PENDING"
    NEEDS_INFO = "NEEDS_INFO"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class TransactionType(StrEnum):
    PURCHASE = "PURCHASE"
    REFUND = "REFUND"
    BALANCE_SYNC = "BALANCE_SYNC"


class ManualPriceStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    EXPIRED = "EXPIRED"


class PriceSource(StrEnum):
    API = "API"
    MANUAL = "MANUAL"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"


class AdminRole(StrEnum):
    USER = "USER"
    ADMIN = "ADMIN"
    SUPERADMIN = "SUPERADMIN"


class FarmPlotState(StrEnum):
    LOCKED = "LOCKED"
    EMPTY = "EMPTY"
    PLANTED = "PLANTED"
    WATER_NEEDED = "WATER_NEEDED"
    GROWING = "GROWING"
    READY = "READY"
    WITHERED = "WITHERED"
