from typing import Protocol

from app.integrations.providers.myxvest.schemas import (
    GiftPurchaseRequest,
    PremiumPurchaseRequest,
    ProviderBalance,
    ProviderOrderResult,
    ProviderOrderStatus,
    ProviderService,
    StarsPurchaseRequest,
)


class ProviderClient(Protocol):
    async def health_check(self) -> bool: ...
    async def get_balance(self) -> ProviderBalance: ...
    async def get_services(self) -> list[ProviderService]: ...
    async def buy_stars(self, request: StarsPurchaseRequest) -> ProviderOrderResult: ...
    async def buy_premium(self, request: PremiumPurchaseRequest) -> ProviderOrderResult: ...
    async def buy_gift(self, request: GiftPurchaseRequest) -> ProviderOrderResult: ...
    async def get_order_status(self, provider_order_id: str) -> ProviderOrderStatus: ...
